### ISSUE TITLE
Связь SongsActivity c PlaylistActivity

### ISSUE THREAD

**Issue by panichev** [panichev/mStreamAndroidClient#4]

**Comment by WolfWood72** [comment]
> Load a playlist
> 
> URL
> 
> /playlist/load
> 
> Method:
> 
> POST
> 
> Request Params
> 
> Required: playlistname - The name of the playlist
> 
> Success Response:
> 
> Code: 200 
> Content: [{filepath: 'path/to/file1.mp3', metadata: ''}, {filepath: 'path/to/file2.flac', metadata: ''}]
> 
> metadata fields are currently blank. A cache layer needs to be built before it's fast enough to lookup 
> metadata for an entire playlists
Таким образом,получать адекватное название песни из плейлиста нормальным образом пока что нельзя. Запрос возвращает только путь до файла. Теоретически, можно сначала получить пути до файла со всего плейлиста,а потом для каждого,отдельным запросом, получать метаданные. Но это будет очень небыстро и некруто. Надо посмотреть каким образом это реализовано непосредственно в mstream, но есть подозрение,что именно так.
На данный момент, в нашем плеере таки выводятся просто пути до файлов,поэтому эту задачу не закрываю

**Comment by WolfWood72** [comment]
Хотя вот в их мобильном приложении такая же хрень

**Comment by WolfWood72** [comment]
В их приложении другая хрень
У них там везде отображается название файла.В альбомах как минимум.А плейлисты вообще не работают. Так что у нас уже лучше =) Такие дела
